"""Initial migration

Revision ID: 326aef1e99cb
Revises: 
Create Date: 2024-07-02 09:09:26.334046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '326aef1e99cb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permission_id'), 'permission', ['id'], unique=False)
    op.create_index(op.f('ix_permission_name'), 'permission', ['name'], unique=True)
    op.drop_index('ix_singin_email', table_name='singin')
    op.drop_index('ix_singin_id', table_name='singin')
    op.drop_index('ix_singin_name', table_name='singin')
    op.drop_index('ix_singin_otp', table_name='singin')
    op.drop_index('ix_singin_password', table_name='singin')
    op.drop_index('ix_singin_phone_number', table_name='singin')
    op.drop_table('singin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('singin',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('phone_number', sa.INTEGER(), nullable=True),
    sa.Column('password', sa.VARCHAR(), nullable=True),
    sa.Column('otp', sa.VARCHAR(), nullable=True),
    sa.Column('expires_at', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('refresh_token', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_singin_phone_number', 'singin', ['phone_number'], unique=1)
    op.create_index('ix_singin_password', 'singin', ['password'], unique=False)
    op.create_index('ix_singin_otp', 'singin', ['otp'], unique=False)
    op.create_index('ix_singin_name', 'singin', ['name'], unique=False)
    op.create_index('ix_singin_id', 'singin', ['id'], unique=False)
    op.create_index('ix_singin_email', 'singin', ['email'], unique=1)
    op.drop_index(op.f('ix_permission_name'), table_name='permission')
    op.drop_index(op.f('ix_permission_id'), table_name='permission')
    op.drop_table('permission')
    # ### end Alembic commands ###
